In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
df = pd.read_csv("house_price_dataset.csv")
df

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Garage       Location  \
0   1  1800       3.0        2.0       1       2005     2.0       New York   
1   2  2200       4.0        3.0       2       2010     NaN    Los Angeles   
2   3  1500       2.0        1.0       1       1998     1.0        Chicago   
3   4  2500       5.0        3.0       2       2015     2.0  San Francisco   
4   5  1700       3.0        NaN       1       2000     1.0       New York   
5   6  2000       4.0        2.0       2       2012     2.0    Los Angeles   
6   7  1200       2.0        1.0       1       1995     NaN        Chicago   
7   8  2600       4.0        3.0       2       2018     2.0  San Francisco   
8   9  1900       3.0        2.0       1       2008     1.0       New York   
9  10  2100       NaN        2.0       2       2011     2.0    Los Angeles   

    Price  
0  450000  
1  550000  
2  320000  
3  800000  
4  400000  
5  600000  
6  280000  
7  850000  
8  470000  
9  520000

In [32]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     1
Bathrooms    1
Floors       0
YearBuilt    0
Garage       2
Location     0
Price        0
dtype: int64

In [33]:
df["Bedrooms"] = df["Bedrooms"].fillna(df["Bedrooms"].median())


In [34]:
df.Bathrooms = df.Bathrooms.fillna(df["Bathrooms"].median())


In [35]:
data_impute = ['Bedrooms' , 'Bathrooms', 'Garage']

for data in data_impute:
    median_value = df[data].median()
    print(f"filling missing value in'{data}' with median {median_value}")
    df[data] = df[data].fillna(median_value)

filling missing value in'Bedrooms' with median 3.0
filling missing value in'Bathrooms' with median 2.0
filling missing value in'Garage' with median 2.0


In [36]:
df

Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Garage       Location  \
0   1  1800       3.0        2.0       1       2005     2.0       New York   
1   2  2200       4.0        3.0       2       2010     2.0    Los Angeles   
2   3  1500       2.0        1.0       1       1998     1.0        Chicago   
3   4  2500       5.0        3.0       2       2015     2.0  San Francisco   
4   5  1700       3.0        2.0       1       2000     1.0       New York   
5   6  2000       4.0        2.0       2       2012     2.0    Los Angeles   
6   7  1200       2.0        1.0       1       1995     2.0        Chicago   
7   8  2600       4.0        3.0       2       2018     2.0  San Francisco   
8   9  1900       3.0        2.0       1       2008     1.0       New York   
9  10  2100       3.0        2.0       2       2011     2.0    Los Angeles   

    Price  
0  450000  
1  550000  
2  320000  
3  800000  
4  400000  
5  600000  
6  280000  
7  850000  
8  470000  
9  520000

In [37]:
from sklearn.preprocessing import LabelEncoder
ft = LabelEncoder()
df["City_Location"] = ft.fit_transform(df["Location"])

In [38]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [39]:
model.fit(df[['Area','Bedrooms','Bathrooms', 'Floors','YearBuilt', 'Garage', 'City_Location']], df.Price)

LinearRegression()

In [41]:
model.predict([[2200,4,3,2,2010,2,2]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([600961.53846154])

In [3]:
import pandas as pd


In [4]:
df = pd.read_csv("simple_house_price_dataset.csv")
df.head(5)

Location    Price
0       New York   913451
1         Austin   552566
2       New York   960311
3  San Francisco  1097576
4        Chicago   427847

In [15]:
data = pd.get_dummies(df.Location)
data.astype(int)

Austin  Chicago  Los Angeles  New York  San Francisco  Seattle
0        0        0            0         1              0        0
1        1        0            0         0              0        0
2        0        0            0         1              0        0
3        0        0            0         0              1        0
4        0        1            0         0              0        0
..     ...      ...          ...       ...            ...      ...
95       1        0            0         0              0        0
96       0        0            1         0              0        0
97       0        0            0         1              0        0
98       0        1            0         0              0        0
99       0        1            0         0              0        0

[100 rows x 6 columns]

In [20]:
merge = pd.concat([df, data], axis = "columns")
merge

Location    Price  Austin  Chicago  Los Angeles  New York  \
0        New York   913451   False    False        False      True   
1          Austin   552566    True    False        False     False   
2        New York   960311   False    False        False      True   
3   San Francisco  1097576   False    False        False     False   
4         Chicago   427847   False     True        False     False   
..            ...      ...     ...      ...          ...       ...   
95         Austin   578941    True    False        False     False   
96    Los Angeles   913930   False    False         True     False   
97       New York   980011   False    False        False      True   
98        Chicago   486938   False     True        False     False   
99        Chicago   463055   False     True        False     False   

    San Francisco  Seattle  
0           False    False  
1           False    False  
2           False    False  
3            True    False  
4           False    False  
..            ...      ...  
95          False    False  
96          False    False  
97          False    False  
98          False    False  
99          False    False  

[100 rows x 8 columns]

In [21]:
final = merge.drop(["Location", "Seattle"], axis = "columns")

In [22]:
final

Price  Austin  Chicago  Los Angeles  New York  San Francisco
0    913451   False    False        False      True          False
1    552566    True    False        False     False          False
2    960311   False    False        False      True          False
3   1097576   False    False        False     False           True
4    427847   False     True        False     False          False
..      ...     ...      ...          ...       ...            ...
95   578941    True    False        False     False          False
96   913930   False    False         True     False          False
97   980011   False    False        False      True          False
98   486938   False     True        False     False          False
99   463055   False     True        False     False          False

[100 rows x 6 columns]

In [23]:
colums = ["Austin", "Chicago", "Los Angeles", "New York", "San Francisco"]
final[colums] = final[colums].astype(int)

In [24]:
final

Price  Austin  Chicago  Los Angeles  New York  San Francisco
0    913451       0        0            0         1              0
1    552566       1        0            0         0              0
2    960311       0        0            0         1              0
3   1097576       0        0            0         0              1
4    427847       0        1            0         0              0
..      ...     ...      ...          ...       ...            ...
95   578941       1        0            0         0              0
96   913930       0        0            1         0              0
97   980011       0        0            0         1              0
98   486938       0        1            0         0              0
99   463055       0        1            0         0              0

[100 rows x 6 columns]

In [26]:
from sklearn.linear_model import LinearRegression

In [31]:
x = final.drop(columns = ["Price"])
x

Austin  Chicago  Los Angeles  New York  San Francisco
0        0        0            0         1              0
1        1        0            0         0              0
2        0        0            0         1              0
3        0        0            0         0              1
4        0        1            0         0              0
..     ...      ...          ...       ...            ...
95       1        0            0         0              0
96       0        0            1         0              0
97       0        0            0         1              0
98       0        1            0         0              0
99       0        1            0         0              0

[100 rows x 5 columns]

In [33]:
y = final.Price
y

0      913451
1      552566
2      960311
3     1097576
4      427847
       ...   
95     578941
96     913930
97     980011
98     486938
99     463055
Name: Price, Length: 100, dtype: int64

In [35]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [36]:
model.predict([[1,0,0,0,0]])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([551073.07692308])

In [37]:
model.score(x,y)

0.9851273491735106

In [2]:
import pandas as pd
df = pd.read_csv("house_price_encoding_dataset.csv")
df

ID       Location House_Type Quality  Bedrooms Parking    Price
0     1         Austin      Villa  Medium         5     Yes   780000
1     2    Los Angeles  Townhouse     Low         2     Yes   343000
2     3        Chicago      Villa     Low         5     Yes   377000
3     4  San Francisco  Townhouse     Low         3     Yes   397000
4     5  San Francisco  Apartment     Low         1      No   330000
..  ...            ...        ...     ...       ...     ...      ...
95   96    Los Angeles  Townhouse     Low         4     Yes   363000
96   97  San Francisco      Villa     Low         3     Yes   461000
97   98        Chicago      Villa  Medium         1      No   790000
98   99  San Francisco  Apartment    High         1      No  1450000
99  100  San Francisco      Villa  Medium         5     Yes  1105000

[100 rows x 7 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dff = df
colums = ["Location", "House_Type", "Quality", "Parking"]
for col in colums:
    dff[col] = le.fit_transform(dff[col])

In [9]:
dff

ID  Location  House_Type  Quality  Bedrooms  Parking    Price
0     1         0           2        2         5        1   780000
1     2         2           1        1         2        1   343000
2     3         1           2        1         5        1   377000
3     4         4           1        1         3        1   397000
4     5         4           0        1         1        0   330000
..  ...       ...         ...      ...       ...      ...      ...
95   96         2           1        1         4        1   363000
96   97         4           2        1         3        1   461000
97   98         1           2        2         1        0   790000
98   99         4           0        0         1        0  1450000
99  100         4           2        2         5        1  1105000

[100 rows x 7 columns]

In [14]:
X = dff[["Location", "House_Type", "Quality", "Bedrooms", "Parking"]].values

In [16]:
y = dff.Price

In [20]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
x = ohe.fit_transform(X).toarray()
x

array([[1., 0., 0., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.]])

In [21]:
xe = x[:,1:]
xe

array([[0., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.]])

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [23]:
model.fit(xe, y)

LinearRegression()

In [26]:
model.score(xe,y)

0.9802932905017983

In [29]:
model.predict([[1,0,1,1,1,1,0,0,0,1,1,1,0,0,0,1,0,0]])

array([808593.61072242])